[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
journal = "3w6dJNqS1rxksirovF8jBCusgrvE5CjQdx71PxZa26Qn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
